unisa-hpc/sycl-bench

CMakeLists.txt
CMake always creates a cache entry for CMAKE_BUILD_TYPE, even if it's
empty. Variables that are present in the cache should always be updated
rather than *shadowed*.
FORCE is needed to update a cache entry that already exists.
see https://cmake.org/cmake/help/v3.16/command/set.html#set-cache-entry
=> CMake: Fix setting of default build type

README.md, include/common.h, pattern/reduction.cpp, pattern/segmentedreduction.cpp, runtime/dag_task_throughput.cpp, single-kernel/scalar_prod.cpp
Use `--no-ndrange-kernels` to disable tests with ndrange parallel for as this will be prohibitively slow with triSYCL and hipSYCL CPU backends
=> Add option to disable ndrange parallel for kernels

CMakeLists.txt, micro/pattern_shared.cpp, pattern/reduction.cpp, polybench/2DConvolution.cpp, polybench/2mm.cpp, polybench/3DConvolution.cpp, polybench/3mm.cpp, polybench/atax.cpp, polybench/bicg.cpp, polybench/correlation.cpp, polybench/covariance.cpp, polybench/fdtd2d.cpp, polybench/gemm.cpp, polybench/gesummv.cpp, polybench/gramschmidt.cpp, polybench/mvt.cpp, polybench/syr2k.cpp, polybench/syrk.cpp, runtime/dag_task_throughput_independent.cpp, runtime/dag_task_throughput_sequential.cpp, single-kernel/kmeans.cpp, single-kernel/lin_reg.cpp, single-kernel/median.cpp, single-kernel/mol_dyn.cpp, single-kernel/sobel.cpp, single-kernel/sobel5.cpp, single-kernel/sobel7.cpp
With these changes, I can now successfully compile all benchmarks using ComputeCpp 1.2.0. The issues were mostly related to kernels implicitly capturing `this` (which is not allowed). This also fixes some warnings for locally declared kernel names (by moving the forward declaration to global scope).
Note that not all benchmarks appear to work correctly for me at the moment. Specifically, I get a segfault for `reduction` and the verification fails for polybench's `correlation`. However these might be due to me using the experimental PTX backend.
=> Fix ComputeCpp compilation errors

CMakeLists.txt, bin/run-suite, single-kernel/median.cpp, single-kernel/sobel.cpp, single-kernel/sobel5.cpp, single-kernel/sobel7.cpp
This installs benchmarks to subdirectory bin/benchmarks instead of bin/. Very likely fixes some reported cases of the `run-suite` script trying to run itself as a benchmark. Also makes the directory layout clearer, emphasizing the role of the `run-suite` script as master program to run all the benchmarks:
```
bin/
run-suite
benchmarks/
benchmark0
benchmark1
benchmark2
...
```
=> Install benchmarks to subdirectory bin/benchmarks instead of bin/

include/common.h, micro/pattern_L2.cpp, micro/pattern_arith.cpp, micro/pattern_sf.cpp, micro/pattern_shared.cpp
This extends the BenchmarkManager to make use of SFINAE to dispatch calls to `verify()` only if the function is implemented on a given benchmark.
If not implemented, instead of simply reporting "PASS", verification will now be properly indicated as not available ("N/A") in the generated output.
=> Allow benchmarks to not implement verify()

include/time_meas.h
This causes the benchmarks to also save the measured invdividual runtime samples in the csv. This can be useful if a more in-depth statistical analysis is required compared to the built-in standard deviation calculation.
=> Save individual runtime samples in result for more sophisticated statistical analysis

include/benchmark_traits.h, include/common.h, include/result_consumer.h, include/time_meas.h, micro/DRAM.cpp
This adds the ability for benchmarks to provide a `getThroughputMetric` function, which returns a metric (e.g. GiB) that can be used to compute throughput (e.g. GiB/s), as well as its unit string. The framework then computes the maximum throughput using the minimum running time measured.
Additionally change the "comment" field of `ResultConsumer::consumeResult` to be a "unit" instead, as that is the only thing we use it for.
=> Add generic throughput metric

CMakeLists.txt, include/command_line.h, include/common.h, micro/DRAM.cpp
This adds experimental support for the "LLVM" and "LLVM-CUDA" SYCL implementations,  corresponding to Intel's DPC++ and Codeplay's fork for targeting CUDA, respectively.
The SYCL compiler needs to be specified using CMAKE_CXX_COMPILER.
=> Add experimental support for LLVM SYCL

include/prefetched_buffer.h
SYCL 2020 does not allow mutable kernels, so InitializationDummyKernel::operator() must be const. Otherwise e.g. DPC++ cannot compile SYCL-Bench.
=> Make InitializationDummyKernel::operator() const

single-kernel/scalar_prod.cpp
This fixes a duplicate kernel name problem in this benchmark that presumably prevents it from building for all implementations (verified with DPC++ and computecpp).
Signed-off-by: jack.kirk <jack.kirk@codeplay.com>
=> Templated ScalarProdGatherKernel fix

polybench/gramschmidt.cpp, polybench/mvt.cpp
For `gramschmidt`, without the change in this PR, then `A` is actually not initialized, as the loop nest is never entered. It happens that elements of `A` are all zeros. In the kernels, when we do multiplication, reductions, etc on zeros, they will give us zeros. In the cpu code `gramschmidt()`, again loop nests are not entered, and elements of `A` continue to be zeros. End up we always verify even if we do nothing at all in the kernels.
For `mvt`, in the kernels `x1` and `x2` are calculated as `x1[i] += a[{i, j}] * y1[j];` and `x2[k] += a[{k, l}] * y2[l];`, if elements of `y1` and `y2` are always zeros, then elements of `x1` and `x2` are always zeros too. Given that elements of `x1` and `x2` are initialized to zeros, it always verify even if we do nothing at all in the kernels. It is …
=> Fix `gramschmidt` and `mvt`

pattern/reduction.cpp
Fix the `reduction` benchmark. Verification fails because the wrong index of the final output buffer is accessed, due to the host accessor being created with a wrong offset.
=> Fix verification for reduction

single-kernel/nbody.cpp
Verification of this benchmark may fail for lower precision types as the underlying driver might replace the `sycl::rsqrt` builtin call with an `llvm.sqrt` intrinsic and an `fdiv` instruction for optimization levels other than `-O0`.
The new verification function does not depend on the number of inputs and uses relative error. Also, maximum allowed error depends on type precision now.
=> Revamp `nbody` verification

include/common.h, micro/DRAM.cpp, micro/arith.cpp, micro/local_mem.cpp, micro/pattern_L2.cpp, micro/sf.cpp, pattern/reduction.cpp, pattern/segmentedreduction.cpp, polybench/fdtd2d.cpp, single-kernel/kmeans.cpp, single-kernel/lin_reg_coeff.cpp, single-kernel/lin_reg_error.cpp, single-kernel/nbody.cpp, single-kernel/scalar_prod.cpp, single-kernel/vec_add.cpp
Check `fp64` aspect at runtime before launching benchmarks using that type. This will allow runtime errors on devices lacking that aspect.
=> Check `double` type support before using it in benchmarks

single-kernel/mol_dyn.cpp
Similar to #52, use relative error for validation rather than difference here.
We ended up with some issues with number very small differences (ratio of computed vs expected being 0.999999 but the fabs of the difference end up being 0.75).
=> Use relative error for mol_dyn validation

CMakeLists.txt, include/prefetched_buffer.h, include/time_metrics.h, include/type_traits.h, spec_constants/spec_constant_convolution.cpp
This PR adds a benchmark which measures the performance impact of specialization constants.
Note that it also includes minor updates to the build process, and to the way results are printed.
The benchmark runs a basic 2D convolution with a generic 3x3 stencil, of which only 5 points are non-zero.  
This seems like a good approximation of a useful and representative use case to me.
In order to better interpret the quality of the results, the following **ways to specify weights** are included:
1. fully dynamically (`AccessVariants::dynamic_value`),
2. as specialization constants (`AccessVariants::spec_const_value`), or
3. statically at compile time (`AccessVariants::constexpr_value`)
Of these, the expectation would be for option 1. to serve as an upper boundary on execution time, and option …
=> Add specialization constant convolution benchmark, other minor updates

CMakeLists.txt, micro/DRAM.cpp, micro/arith.cpp, micro/local_mem.cpp, micro/pattern_L2.cpp, micro/sf.cpp, pattern/reduction.cpp, pattern/segmentedreduction.cpp, polybench/fdtd2d.cpp, single-kernel/kmeans.cpp, single-kernel/lin_reg_coeff.cpp, single-kernel/lin_reg_error.cpp, single-kernel/nbody.cpp, single-kernel/scalar_prod.cpp, single-kernel/vec_add.cpp
This PR adds a cmake variable `SYCL_BENCH_ENABLE_FP64_BENCHMARKS` to explicitly enable FP64 benchmarks. The variable is set to `1` or `0` with a define in the C++ code.  
This is required as AoT compilation can fail if the target device does not support FP64 (e.g. desktop Intel GPUs), thus the current way of querying the FP64 aspect at runtime is not sufficient.
=> Enable FP64 benchmarks at compile time

README.md, bin/run-suite, include/command_line.h, include/time_metrics.h
Add option to perform a first "warmup" run that will not be taken into consideration to omit possible JIT overhead in the evaluation.
Also add two additional profiles to `run-suite`: `cpu-warmup` and `gpu-warmup`.
=> Add `--warmup-run` option

CMakeLists.txt, README.md
Add several `CPACK_*` options and `package` and `package_source` targets to configure and build SYCL-Bench packages.
=> Add CPack capabilities to CMakeLists.txt

single-kernel/median.cpp
The `median` bennchmark was not loading the image correctly. 
- moved Brommy.bmp to `share` directory
- median benchmark now loads the picture using a path local to the build directory
=> Fix `median` benchmark image load

CMakeLists.txt
- Fixed the command line parameter string for Intel GPUs on DPC++
- Added some default cmake arguments for debug, release and ReleaseWithDebugInfo
=> Fix DPC++ Intel GPU cmake + default cmake arguments 

include/time_metrics.h
When using the `--warmup-run` flag with verification on, if the verification fails only the warmup run is executed. This was leading to segfault as the warmup run was skipping the first execution in every case. This PR adds a check before skipping the run.
Fixes #75.
=> Add check for `timingResults` size when using `--warmup-run`

CMakeLists.txt
Somewhere in time, the default build flags got duplicated in the CmakeLists.txt.
This PR removes the duplicated one.
=> Removed duplicated default build flags

sycl2020/spec_constants/spec_constant_convolution.cpp
This PR adds support for AdaptiveCpp `sycl::specialized` to the specialization constant benchmark.
While the AdaptiveCpp extension is not technically a spec constant implementation, it serves the same purpose therefore I think it's correct to include it in SYCL-Bench.
=> Add AdaptiveCPP `sycl::specialized` support for specialization constant benchmark
